language: generic
sudo: required
services:
- docker
before_install:
- docker build -t etiadam/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true etiadam/docker-react npm run test -- --coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: mJdbf3ZWsbCXctoScPeQSSwO+x35oGM5jGU6IXkLnAd90kVLBSZHf8OcRKuOKzQuKMrlv7SFfv/cEc+F4jvhqAlpOgdKpEbMXRyhqpwg6EA8wCyZPknHMTZ3nVOyNpdd4ruyY2662Wt+dm4FkqaAtEYEneeelz2Gro2rzVKqSuAqqGvJfjBf46b7edan7NW2VZCtQPyz1ZL/puabk754i2l1GQlNfETUq0732p0hvukhsNuqvk+U36AovXls2rs8USdR8uliKXlQbG6L3PJ9M6YP1CFx11DlZCtjl7Wb4CN9zJnrYEzUyDYgKudanhYtABoE2Tr2LDLaVG8TZlYPRA6/tI8ZE6aPUahiAj3f6vRVgadK+MWXJek6k5pLTtVgUleZA18P8boPyBzGnAGMjBOfbI4bLmIsyzabD9O+splytbFAEhu3ZY804h3C9NwKENNU0FGt5sgt5XWo9AfB4C5fZJ+kXZGY91F9Z5LP+CmC4KPgtLNbF8JdnpajhcQJnjsLH98gLlKakiHOZA+8PBux7xpaKbL4b3f9kUgqm1L3RsGxgwGGrtrIgP33IN/dLegvbhH1Pgx8Bx82AclIDrO+XfJIjV+/naytmKJP6jjLw8rc80HKxho5OTN6LLdITvQwTFM/uMEZYye93tZlRnwv8N33Vt1i8ctMKb17NMM=
  app: docker-react-eti
  on:
    branch: master
    repo: Etiadam/docker-react
