language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t etiadam/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true etiadam/docker-react npm run test -- --coverage

deploy:
    provider: heroku
    # region: "United States"   
    api_key:
        secure: "e94c33bf-4781-4547-92b0-0acc4df8afbf"
    app: "docker-react-eti"
    on: 
        branch: master