language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t etiadam/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true etiadam/docker-react npm run test -- --coverage

deploy:
    provider: heroku
    skip_cleanup: true
    # region: "United States"   
    api_key:
        secure: "2fdb57df-20f1-4523-a688-d758505d3e71"
    app: "docker-react-eti"
    on: 
        branch: master
        repo: Etiadam/docker-react
    # access_key_id: "$HEROKU_OAUTH_ID"
    # secret_access_key:
    #     secure: "$HEROKU_OAUTH_SECRET"